<div class='container'>
<div class='masthead'>
<div class='brand'>
<a href="/2015/index.shtml"><img title="Там Куи Кхи Конг" class="logo" src="/2015/img/planka-right.jpg" alt="Logo" />
</a>
</div>
<header> Федерация Там Куи Кхи-конг. Индивидуальные и групповые занятия +7 (495) 769-72-00 </header>
<nav>
<ul class='nav nav-justified'>
<!-- <li><a href="#">Главная</a></li>  -->
<li><a href="/2015/adresa-zalov.shtml">Адреса залов</a></li>
<li><a href="/2015/video-tamqui.shtml">Видео</a></li>
<li><a href="/2015/knigi.shtml">Книги</a></li>
<li><a href="/2015/boevoe-iskusstvo.shtml">Боевое искусство</a></li>
<li><a href="/2015/khi-yoga.shtml">Кхи-йога</a></li>
<li><a href="/2015/podrostki.shtml">Для подростков</a></li>
<li><a href="/2015/zanim.shtml">Занимающимся</a></li>
<li><a href="/2015/velichie-dzen.shtml">Величие Дзен</a></li>

</ul>
</nav>
</div>
